services:

  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slack-ai-agent-app
    restart: always

    ports:
      - "6969:6969"
    environment:
      CHAT_LOG_DIR: ${CHAT_LOG_DIR}
      CHAT_JSON_DIR: ${CHAT_JSON_DIR}
      CHAT_LOG_FILENAME: ${CHAT_LOG_FILENAME}

      CHAT_SERVER_ADDRESS: ${CHAT_SERVER_ADDRESS}
      CHAT_SERVER_PORT: ${CHAT_SERVER_PORT}

      CHAT_DB_HOST: ${CHAT_DB_HOST}
      CHAT_DB_NAME: ${CHAT_DB_NAME}
      CHAT_DB_PORT: ${CHAT_DB_PORT}
      CHAT_DB_USERNAME: ${CHAT_DB_USERNAME}
      CHAT_DB_PASSWORD: ${CHAT_DB_PASSWORD}

      CHAT_MODEL: gpt-5.1
      CHAT_MAX_TOKENS: 1240

      GPT_CHAT_API_KEY: ${GPT_CHAT_API_KEY}
      GPT_CHAT_SYSTEM_INITIAL_MESSAGE: Always mention user when responding. If i ask you to mention all, type <!channel>. You are very friendly slack-ai-agent.

      TS_HOST: ${TS_HOST}
      TS_HTTP_PORT: ${TS_HTTP_PORT}
      TS_BOT_EMAIL: test@test.com
      TS_BOT_PW: ${TS_BOT_PW}
      TS_BOT_SLACK_USER_ID: USLACKBOT

      SLACK_CHANNEL_ID: ${SLACK_CHANNEL_ID}
      SLACK_BOT_OAUTH_TOKEN: ${SLACK_BOT_OAUTH_TOKEN}

      JIRA_KEY: ${JIRA_KEY}

      CHAT_ALLOW_FUNCTION_ASSIGNTASKSYSTEMISSUETOOL : 1
      CHAT_ALLOW_FUNCTION_CREATEJIRAISSUETOOL : 0
      CHAT_ALLOW_FUNCTION_CREATETASKSYSTEMISSUETOOL : 1
      CHAT_ALLOW_FUNCTION_GETISSUESBYSLACKUSERIDTOOL : 1
      CHAT_ALLOW_FUNCTION_GETALLTASKSYSTEMISSUESTOOL : 1
      CHAT_ALLOW_FUNCTION_GETALLJIRAISSUESTOOL:
      CHAT_ALLOW_FUNCTION_GITHUBGETREPOSTOOL : 0

    volumes:
      - /var/log/slackagent:/var/log:Z