name: Build and Deploy Spring Boot App on Live server container

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Sync project to server
        run: |
          rsync -avz --delete \
            --exclude ".git" \
            --exclude "target" \
            ./ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR_DOCKER }}/

      - name: Deploy on server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e

            cd ${{ secrets.WORK_DIR_DOCKER }}

            printf '%s\n' \
              "CHAT_DB_PASSWORD=${{ secrets.CHAT_DB_PASSWORD }}" \
              "GPT_CHAT_API_KEY=${{ secrets.GPT_CHAT_API_KEY }}" \
              "TS_BOT_PW=${{ secrets.TS_BOT_PW }}" \
              "SLACK_CHANNEL_ID=${{ secrets.SLACK_CHANNEL_ID }}" \
              "SLACK_BOT_OAUTH_TOKEN=${{ secrets.SLACK_BOT_OAUTH_TOKEN }}" \
              "JIRA_KEY=${{ secrets.JIRA_KEY }}" \
              "TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }}" \
              "CHAT_DB_HOST=192.168.1.11" \
              "CHAT_DB_NAME=chatgpt-integration" \
              "CHAT_DB_PORT=5432" \
              "CHAT_SERVER_ADDRESS=0.0.0.0" \
              "CHAT_SERVER_PORT=6969" \
              "TS_HOST=192.168.1.11" \
              "TS_HTTP_PORT=6901" \
              "CHAT_DB_USERNAME=chatgpt" \
              "CHAT_LOG_DIR=/var/log" \
              "CHAT_JSON_DIR=/var/json" \
              "CHAT_LOG_FILENAME=chatgpt" \
              > .env

            docker compose down || true
            docker compose up -d --build

            docker ps
          EOF

      - name: Show containers
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker ps"

      - name: Cleanup SSH
        if: always()
        run: rm -rf ~/.ssh